name: SAT-Pol
version: '0.1.0.0'
category: Tool
author: Daniel R. Chavarria
maintainer: drodriguez15@us.es
copyright: Daniel R. Chavarria
license: BSD3
homepage: https://github.com/githubuser/SAT-Pol#readme
extra-source-files:
- README.org
dependencies:
- base >=4.7 && <5
- HaskellForMaths
- containers
- hatt
- doctest
library:
  source-dirs: src
  exposed-modules:
  - PolAux
  - Tool
  - Examples
  - ReadingF
tests:
  doctests:
    main: Doctest.hs
    source-dirs: test
    ghc-options: -threaded
    dependencies:
    - doctest-discover
